#!/usr/bin/env python3
import sys
import os
from pathlib import Path

LBIN=Path(__file__).absolute().parent/'lbin'

def rchildren(path):
    yield path
    for child in path.glob('*'):
        yield from rchildren(child)
def main():
    for path in rchildren(LBIN):
        if path.is_file():
            rpath=path.relative_to(LBIN)
            if path.name=='__main__':
                rpath=rpath.parent
            cmd = str(rpath).replace('/','-')
            print(cmd, rpath, path)
if __name__ == '__main__':
    main()
