#!/source/this/sh
mkdir -p ~/.local/bin


export_ () { export $1=$2; }
export_ POET_ARGS   "$*"
export_ POET        $(dirname ${PWD})
export_ POET_BIN    ${POET}/bin
export_ POET_LBIN   ~/.local/bin
export_ POET_LOG    ${HOME}/.poet.log
export_ PATH        ${PATH}:${POET_BIN}
export_ PATH        ${PATH}:${POET_LBIN}
export_ PATH        $(poet.path  clean)
export_ POET_BLESSED ${HOME}/.__blessed__

poet_install () { ${POET}/.insitu/install ; }
monty () { . poet.activate monty; }
largo () { . poet.activate poet; }

# Activation of [poet] in necessary every time. 
# It has vital aliases that the current end user
# needs at all times.

largo

echo "Type 'poet_install' to install blessed clients."
echo "Type 'monty' to activate the monty prompt"
echo "Type 'largo' to activate the largo poet."
