#!/source/this/sh
export_ () { export $1=$2; }
export_ POET        $(dirname ${PWD})
export_ POET_BIN    ${POET}/bin
export_ POET_USER   ${POET}/user
export_ POET_POEM   ${POET}/poem
export_ POET_VENDOR ${POET}/.vendor
export_ PATH        ${POET_BIN}:${PATH}
export_ PO_BIN      ${POET}/po
export_ PATH        $(./path.py clean)
mkdir -p            ${HOME}/.local/bin/
cp ${POET}/lbin/*   ${HOME}/.local/bin/

# install our own [po] command suite.

 po () {   blessed.po     $*; }
.po () { . blessed.po.src $*; }

.po bless -u $POET poem -b main
.po bless -u $POET bozo
.po bless -u $POET bch
.po bless -u $POET monty

# activate the dotfile via blessed.bozo.
. blessed.bozo.src dot $*

