#!/bin/sh
a="[$POET_USER/dotfiles/startup]\n\t$*"
b="Type [user] for user friendliness."
> /dev/stderr printf "\n\t$a\n\t$b\n\n"

user () {
    fn_magic_monty
}

fn_magic_monty () {
    local dst=~/.local/var/poet/magicmonty/bash-git-prompt
    local src=https://github.com/magicmonty/bash-git-prompt
    [ $1. = install. ] && rm -rf ${dst}
    [ ! -d ${dst} ] && echo installing monty
    [ ! -d ${dst} ] && git clone ${src} ${dst}
    . ${dst}/gitprompt.sh
}




