#!/bin/sh
main () {
    local p=${PO_BIN}/po
    [ "$1" == "" ] && { ${p}.__null__ $* ; return $?; }
    [ -f ${p}.$1 ] && { ${p}.$*          ; return $?; }
    [ -f ${p}.$1 ] || { ${p}.__bad__ $*  ; return $?; }
}
main $*
