#!/bin/sh

user () {
    fn_activate_magic_monty
}

fn_activate_magic_monty () {
    echo activating magic monty prompt.
    . ${POET_VENDOR}/github.com/magicmonty/bash-git-prompt/gitprompt.sh
}

fn_hello () {
    a="[poet]: dot$*"
    b="[poet]: type [user] for user friendliness."
    > /dev/stderr printf "\n$a\n$b\n\n"
}

